default_agent: hello_agent
agents:
  hello_agent:
    name: hello_agent
    entrypoint: agent_example.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::068048081706:role/my-AgentCore-runtime-role
      execution_role_auto_create: true
      account: 068048081706
      region: us-east-1
      ecr_repository: 068048081706.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-hello_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
    bedrock_agentcore:
      agent_id: hello_agent-I5Xah3DF7J
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:068048081706:runtime/hello_agent-I5Xah3DF7J
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-hello_agent-builder
      execution_role: arn:aws:iam::068048081706:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-c07010a437
      source_bucket: bedrock-agentcore-codebuild-sources-068048081706-us-east-1
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_o9XzhnwBe/.well-known/openid-configuration
        allowedClients:
        - 7cbt1hugs169ssf7cv9dp8tobt
    oauth_configuration: null
