default_agent: tech_learning_assistant
agents:
  tech_learning_assistant:
    name: tech_learning_assistant
    entrypoint: /Users/tnobe/Desktop/BedrockAgentCoreBasic/memory/tech-learning-assistant/agent_tech_learning_assistant.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::068048081706:role/AgentCoreExecutionRole
      execution_role_auto_create: false
      account: 068048081706
      region: us-west-2
      ecr_repository: 068048081706.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-tech_learning_assistant
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: tech_learning_assistant-FZBhpo4nns
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:068048081706:runtime/tech_learning_assistant-FZBhpo4nns
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-tech_learning_assistant-builder
      execution_role: arn:aws:iam::068048081706:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-cd7deed732
      source_bucket: bedrock-agentcore-codebuild-sources-068048081706-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
