default_agent: my_mcp_server
agents:
  my_mcp_server:
    name: my_mcp_server
    entrypoint: my_mcp_server.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::068048081706:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-cb7bbfb8e9
      execution_role_auto_create: false
      account: 068048081706
      region: us-east-1
      ecr_repository: 068048081706.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-my_mcp_server
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: my_mcp_server-5yc8uaBtKu
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:068048081706:runtime/my_mcp_server-5yc8uaBtKu
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-my_mcp_server-builder
      execution_role: arn:aws:iam::068048081706:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-cb7bbfb8e9
      source_bucket: bedrock-agentcore-codebuild-sources-068048081706-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
