# Install Node.js and npm
RUN apt-get update && apt-get install -y \
    curl \
    && curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
    && apt-get install -y nodejs chromium chromium-driver fonts-noto-cjk libreoffice-impress\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN npm install -g @marp-team/marp-cli